version: "3.9"

services:
  # ===============================
  # 1. AUTH SERVICE (Swarm LB)
  # ===============================
  auth-service:
    image: my-auth-service

    restart: always

    environment:
      - MONGODB_URI=mongodb+srv://nguyentronghieu2kk5_db_user:8OQlHdhPdUCHWxES@cluster0.ttgxlkn.mongodb.net/test?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=hao123
      - JWT_REFRESH_SECRET=hao123

    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 3

  # ===============================
  # 2. DOCUMENT SERVICE (Swarm LB)
  # ===============================
  document-service:
    image: my-document-service

    restart: always

    environment:
      - MONGODB_URI=mongodb+srv://nguyentronghieu2kk5_db_user:8OQlHdhPdUCHWxES@cluster0.ttgxlkn.mongodb.net/test?retryWrites=true&w=majority&appName=Cluster0
      - AUTH_SERVICE_URL=http://auth-service:5001
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 3

  # ===============================
  # 3. WEBSOCKET SERVICE (NGINX LB)
  # ===============================
  websocket-service:
    image: my-websocket-service

    restart: always

    environment:
      - DOCUMENT_SERVICE_URL=http://document-service:5002
      - WS_PORT=5003
      - FRONTEND_ORIGIN=http://localhost:5173
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 3

  # ===============================
  # 4. GATEWAY (OpenResty)
  # ===============================
  gateway:
    image: my-gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    networks:
      - app-network
    depends_on:
      - auth-service
      - document-service
      - websocket-service
    deploy:
      mode: replicated
      replicas: 1

  # ===============================
  # 5. FRONTEND (Vite dev server)
  # ===============================
  client:
    image: my-client
    restart: always
    environment:
      - VITE_APP_BACKEND_URL=http://localhost:80
      - VITE_APP_SOCKET_URL=http://localhost:80

    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - gateway
    deploy:
      mode: replicated
      replicas: 1

# ===============================
# NETWORK
# ===============================
networks:
  app-network:
    driver: overlay
